In [9]:
import nashpy as nash
import numpy as np

In [17]:
# Create the payoff matrix
v=0.7
c=1.0
A = np.array([[(v-c)/2,v],[0,v/2]]) # A is the row player
B = np.array([[(v-c)/2,0],[v,v/2]]) # B is the column player
game2 = nash.Game(A,B)
# Find the Nash Equilibrium with Support Enumeration
equilibria = game2.support_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0.]), array([0., 1.]))
(array([0., 1.]), array([1., 0.]))
(array([0.7, 0.3]), array([0.7, 0.3]))


In [21]:
[[(v-c)/2, v], [0, v/2]]


[[-0.15000000000000002, 0.7], [0, 0.35]]

In [28]:
v=2
c=4
A = np.array([[(v-c)/2, v, (v-c)/2], [0, v/2, v/2], [(v-c)/2, v/2, v/2]])
B = A.T
game = nash.Game(A,B)
# Find the Nash Equilibrium with Support Enumeration
equilibria = game.support_enumeration()
for eq in equilibria:
    print(eq)
# 2/3 D + 1/3 R should be Nash eq, isn't it?

(array([1., 0., 0.]), array([0., 1., 0.]))
(array([0., 1., 0.]), array([1., 0., 0.]))
(array([0., 0., 1.]), array([0., 0., 1.]))
(array([0.5, 0.5, 0. ]), array([0.5, 0.5, 0. ]))


In [18]:
game2

Bi matrix game with payoff matrices:

Row player:
[[-0.15  0.7 ]
 [ 0.    0.35]]

Column player:
[[-0.15  0.  ]
 [ 0.7   0.35]]

In [12]:
A = np.array([[0, -1, 1], [1, 0, -1], [-1, 1, 0]])
rps = nash.Game(A)
rps

Zero sum game with payoff matrices:

Row player:
[[ 0 -1  1]
 [ 1  0 -1]
 [-1  1  0]]

Column player:
[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]

In [13]:
B = - A
rps = nash.Game(A, B)
rps

Zero sum game with payoff matrices:

Row player:
[[ 0 -1  1]
 [ 1  0 -1]
 [-1  1  0]]

Column player:
[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]

In [14]:
eqs = rps.support_enumeration()

list(eqs)

[(array([0.33333333, 0.33333333, 0.33333333]),
  array([0.33333333, 0.33333333, 0.33333333]))]